### PR TITLE
Indicate that the Airbnb Apple TV app has been sunsetted

### PR DESCRIPTION
**Pull request by bachand**
Let's make this clear to anyone who may come across this repo

### CODE REVIEW

**Comment by ljharb** [comment]
After merging this, I’d suggest archiving the repo.

**Comment by bachand** [comment]
@ljharb I can't access the settings of this repo. Can you grant me permission?

**Comment by ljharb** [comment]
I'm afraid I'm no longer empowered to help; perhaps @lencioni can make you an admin?

**Review by dfed — APPROVED** [review]
LGTM. Agree that we should archive since we're not planning on maintaining this repo.

**Comment by bachand** [comment]
If you can help with that @lencioni I would appreciate it. Also happy if you want to archive this yourself.

**Pull request merged**
